/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Product;
import model.ProductCatalog;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import model.CustomerDirectory;
import model.OrderDirectory;

/**
 *
 * @author 80424
 */
public class ProductsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductsPanel
     */
    public ProductsPanel() {
        initComponents();
        productCatalog = new ProductCatalog();
        customerDirectory = new CustomerDirectory();
        orderDirectory = new OrderDirectory();
        
        workArea.add(new ProductsPanel(productCatalog), "PRODUCTS");
        workArea.add(new CustomerOrderPanel(productCatalog, customerDirectory, orderDirectory), "CUSTOMER");
        workArea.add(new SearchPanel(productCatalog, customerDirectory, orderDirectory), "SEARCH");
        workArea.add(new OrderListPanel(productCatalog, customerDirectory, orderDirectory), "ORDERS");
    }
    
    private void showCard(String cardName) {
        java.awt.CardLayout cl = (java.awt.CardLayout) workArea.getLayout();
        cl.show(workArea, cardName);
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
