/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.PersonProfile;
import javax.swing.JOptionPane;

/**
 *
 * @author 80424
 */
public class PersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanel
     */
    PersonProfile personprofile;
    public PersonJPanel(PersonProfile p) {
        initComponents();
        personprofile = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNameP = new javax.swing.JLabel();
        lblAgeP = new javax.swing.JLabel();
        lblGenderP = new javax.swing.JLabel();
        lblPhoneP = new javax.swing.JLabel();
        lblEmailP = new javax.swing.JLabel();
        fieldNameP = new javax.swing.JTextField();
        fieldAgeP = new javax.swing.JTextField();
        fieldGenderP = new javax.swing.JTextField();
        fieldPhoneP = new javax.swing.JTextField();
        fieldEmailP = new javax.swing.JTextField();
        btnSaveP = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("Create a Person");

        lblNameP.setText("Name");

        lblAgeP.setText("Age");

        lblGenderP.setText("Gender");

        lblPhoneP.setText("Phone Number");

        lblEmailP.setText("Email");

        fieldGenderP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldGenderPActionPerformed(evt);
            }
        });

        btnSaveP.setText("Save");
        btnSaveP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneP)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblGenderP)
                        .addComponent(lblAgeP, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNameP, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblEmailP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldAgeP, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(fieldNameP)
                    .addComponent(fieldGenderP)
                    .addComponent(fieldEmailP)
                    .addComponent(fieldPhoneP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnSaveP)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameP)
                            .addComponent(fieldNameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblAgeP))
                    .addComponent(fieldAgeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenderP)
                    .addComponent(fieldGenderP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneP)
                    .addComponent(fieldPhoneP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailP)
                    .addComponent(fieldEmailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnSaveP)
                .addGap(123, 123, 123))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldGenderPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldGenderPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldGenderPActionPerformed

    private void btnSavePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePActionPerformed
        // TODO add your handling code here:
        String name = fieldNameP.getText();
        String age = fieldAgeP.getText();
        String gender = fieldGenderP.getText();
        String phoneNumber = fieldPhoneP.getText();
        String email = fieldEmailP.getText();
        
        personprofile.setName(name);
        personprofile.setAge(age);
        personprofile.setGender(gender);
        personprofile.setPhoneNumber(phoneNumber);
        personprofile.setEmail(email);
        
        JOptionPane.showMessageDialog(this, "Successfully Saved");
        
        fieldNameP.setText("");
        fieldAgeP.setText("");
        fieldGenderP.setText("");
        fieldPhoneP.setText("");
        fieldEmailP.setText("");
        
    }//GEN-LAST:event_btnSavePActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveP;
    private javax.swing.JTextField fieldAgeP;
    private javax.swing.JTextField fieldEmailP;
    private javax.swing.JTextField fieldGenderP;
    private javax.swing.JTextField fieldNameP;
    private javax.swing.JTextField fieldPhoneP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAgeP;
    private javax.swing.JLabel lblEmailP;
    private javax.swing.JLabel lblGenderP;
    private javax.swing.JLabel lblNameP;
    private javax.swing.JLabel lblPhoneP;
    // End of variables declaration//GEN-END:variables
}
