/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.PersonProfile;

/**
 *
 * @author 80424
 */
public class ViewPJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPJPanel
     */
    PersonProfile personprofile;
    public ViewPJPanel(PersonProfile p) {
        initComponents();
        personprofile = p;
        display();
    }

    private void display() {
        fieldNameP.setText(personprofile.getName());
        fieldAgeP.setText(personprofile.getAge());
        fieldGenderP.setText(personprofile.getGender());
        fieldPhoneP.setText(personprofile.getPhoneNumber());
        fieldEmailP.setText(personprofile.getEmail());
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGenderP = new javax.swing.JLabel();
        lblPhoneP = new javax.swing.JLabel();
        lblEmailP = new javax.swing.JLabel();
        fieldNameP = new javax.swing.JTextField();
        fieldAgeP = new javax.swing.JTextField();
        fieldGenderP = new javax.swing.JTextField();
        fieldPhoneP = new javax.swing.JTextField();
        fieldEmailP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNameP = new javax.swing.JLabel();
        lblAgeP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        lblGenderP.setText("Gender");

        lblPhoneP.setText("Phone Number");

        lblEmailP.setText("Email");

        fieldGenderP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldGenderPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("View Person");

        lblNameP.setText("Name");

        lblAgeP.setText("Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneP)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblGenderP)
                        .addComponent(lblAgeP, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNameP, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblEmailP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldAgeP)
                    .addComponent(fieldNameP)
                    .addComponent(fieldGenderP)
                    .addComponent(fieldEmailP)
                    .addComponent(fieldPhoneP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameP)
                            .addComponent(fieldNameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblAgeP))
                    .addComponent(fieldAgeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenderP)
                    .addComponent(fieldGenderP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneP)
                    .addComponent(fieldPhoneP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailP)
                    .addComponent(fieldEmailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldGenderPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldGenderPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldGenderPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAgeP;
    private javax.swing.JTextField fieldEmailP;
    private javax.swing.JTextField fieldGenderP;
    private javax.swing.JTextField fieldNameP;
    private javax.swing.JTextField fieldPhoneP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAgeP;
    private javax.swing.JLabel lblEmailP;
    private javax.swing.JLabel lblGenderP;
    private javax.swing.JLabel lblNameP;
    private javax.swing.JLabel lblPhoneP;
    // End of variables declaration//GEN-END:variables

  
}
